### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by jjqcat** [sutongkui/simulator#6]
你好，这个simulation速度确实飞快，有面料的自碰撞检测吗？另外，面料模拟效果如果再丰富点就完美了

**Comment by sutongkui** [comment]
没有添加自碰撞检测，因为对应特定的场景自碰撞有时不是必须的。你指的模拟效果丰富是什么意思？

**Comment by jjqcat** [comment]
不好意思，我指的是模拟各种面料效果，如丝绸，棉，麻，皮等不同材质的面料属性
